"""
Smart OCR System - Enterprise-grade Chinese OCR Solution

A high-performance OCR system powered by PaddleOCR for accurate
Chinese text recognition with batch processing and multi-format export.

Author: Generated by TaskMaster
Version: 0.1.0
"""

__version__ = "0.1.0"
__author__ = "Smart OCR Team"

from .core.config import OCRConfig
from .core.ocr_engine import OCREngine

__all__ = ["OCREngine", "OCRConfig", "__version__"]
